### ISSUE TITLE
Backend crashes while trying to compose up the stack, on fresh install

### ISSUE THREAD

**Issue by albertcoro** [sitmun/sitmun-admin-app#212]
**Describe the bug**
Trying to reinstall the project I noticed that the Backend crashes while trying to compose up the stack.

**To Reproduce**
1. Run `git clone --recurse-submodules https://github.com/sitmun/sitmun-application-stack.git` on a new folder
2. Run `docker compose build --no-cache`
3. Run `docker compose up`
4. Check the localhost page [http://localhost:9000/admin/#/dashboard](http://localhost:9000/admin/#/dashboard)

**Expected behavior**
It is expected that the backend works correctly and the link above displays the app

**Screenshots**
Screenshot of the docker, with the backend crashed:
![image](https://github.com/user-attachments/assets/029ff99c-a410-4301-8f89-046f4eac83db)

Screenshot of the docker last logs from the backend:
![image](https://github.com/user-attachments/assets/09d12f10-253d-4c5d-94f1-a2d57c755266)

Text of the Last screenshot:
```
Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 46b8b8da1462 (172.18.0.3) since 9/2/24, 6:58 AM
2024-09-18 10:46:28     at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:270) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at liquibase.Liquibase.lambda$update$1(Liquibase.java:214) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at liquibase.Liquibase.runInScope(Liquibase.java:2405) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at liquibase.Liquibase.update(Liquibase.java:211) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at liquibase.Liquibase.update(Liquibase.java:197) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:314) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269) ~[liquibase-core-4.9.1.jar!/:na]
2024-09-18 10:46:28     at org.sitmun.infrastructure.persistence.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:41) ~[classes!/:na]
2024-09-18 10:46:28     at org.sitmun.infrastructure.persistence.liquibase.AsyncSpringLiquibase.afterPropertiesSet(AsyncSpringLiquibase.java:34) ~[classes!/:na]
2024-09-18 10:46:28     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar!/:5.3.31]
2024-09-18 10:46:28     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar!/:5.3.31]
2024-09-18 10:46:28     ... 139 common frames omitted
```

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.138 (Build oficial) (64 bits)

**Comment by fjlopez** [comment]
Did you run `docker compose stop` first?

**Comment by fjlopez** [comment]
The error `Caused by: liquibase.exception.LockException: Could not acquire change log lock. Currently locked by 46b8b8da1462 (172.18.0.3) since 9/2/24, 6:58 AM` indicates that another process on the container `46b8b8da1462` (at `172.18.0.3`) has locked the Liquibase changelog. This typically occurs when a previous Liquibase migration didn't complete properly or was interrupted, leaving the database in a locked state.

### Steps to resolve:

1. **Stop running containers:**
   First, ensure that any related processes are stopped to avoid conflicts:
   ```bash
   docker compose stop
   ```

2. **Remove the volume**
   Next, remove the containers along with the volume associated with the database to reset its state.
   ```bash
   docker compose down -v
   ```

3. **Restart the services:**
   Once the volume is  removed, restart the services to see if the issue has been resolved.
   ```bash
   docker compose up
   ```

**Comment by albertcoro** [comment]
I have to create a new fresh install, but it did work with `docker copose down -v`. Thank you!

**Comment by fjlopez** [comment]
Seems solved.
